language: node_js
node_js:
  - "8"
script: yarn test
notifications:
  email:
    recipients:
      - wchargin+travis-sourcecred@gmail.com
      - decentralion+travis-sourcecred@dandelion.io
    on_failure: always
